baseURL = "https://keremyilmaz.dev"
languageCode = "en-us"
title = "Kerem Yilmaz"
theme="archie"
copyright = "© Kerem Yilmaz"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="toggle"
	useCDN=false
	subtitle = "Software Engineer & Tech Enthusiast"
	
	# Custom CSS
	customcss = ["css/intro.css"]
	
	# Intro section
	showIntro = true
	introPhoto = "/profile.jpg"
	introTitle = "Hi, I'm Kerem Yilmaz"
	introText = "Welcome to my personal website. I'm a software engineer passionate about technology, open source, and building great products. Here you'll find my thoughts, projects, and experiences."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ykeremy"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/ykeremy"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
